version: '3.8'

services:
  core:
    image: xnomadai/core:0.1.5
    container_name: core
    ports:
      - "8080:8080"
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - agent_data:/app/db_data/agent
      - /var/run/tappd.sock:/var/run/tappd.sock
    restart: always
    depends_on:
      - mongodb
    command: >
      sh -c 'node dist/main.js'
volumes:
  agent_data:
    driver: local