version: '3.8'

services:
  phala:
    image: phalanetwork/tappd-simulator:latest
    container_name: phala-tee-simulator
    ports:
      - "8090:8090"
    restart: always
    networks: 
    - core_local
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGO_REPL_SET_NAME=rs0
    command: >
      bash -c "
        mongod --replSet rs0 --bind_ip 0.0.0.0 --bind_ip_all &
        sleep 5 &&
        mongo mongodb:27017 --eval 'rs.initiate()' &&
        wait"
    volumes:
      - ./.db_data/mongo:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "rs.status()"]
      start_period: 5s
      interval: 5s
      retries: 10
      timeout: 30s
networks:
  core_local:
    driver: bridge
