version: '3.8'

services:
  core:
    image: xnomadai/core:0.1.2
    container_name: core
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - ./.db_data/agent:/app/db_data/agent
      - /var/run/tappd.sock:/var/run/tappd.sock
    restart: always
    depends_on:
      - mongodb
    command: >
      sh -c '
        echo "${CORE_SERVER}" | base64 -d > /app/.env &&
        echo "${CORE_AGENT}" | base64 -d > /app/.env.agent-eliza &&
        node dist/main.js'