version: '3.8'

services:
  phala:
    image: phalanetwork/tappd-simulator:latest
    container_name: phala-tee-simulator
    ports:
      - "8090:8090"
    restart: always
    networks: 
    - core_local

  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGO_REPL_SET_NAME=rs0
    command: mongod --replSet rs0 --bind_ip 0.0.0.0 --bind_ip_all
    networks: 
    - core_local

  mongodb-init-replica-set:
    container_name: mongodb-init-replica-set
    image: mongo:4.4
    command: bash -c "sleep 5 && mongo mongodb:27017 --eval 'rs.initiate()'"
    depends_on:
      - mongodb
    networks: 
    - core_local
    deploy:
      resources:
        limits:
          memory: 256m

networks:
  core_local:
    driver: bridge
