version: '3.8'

services:
  wallet-service:
    image: xnomadai/tee:0.1.5
    container_name: wallet-service
    ports:
      - '8080:8080'
    volumes:
      - /var/run/tappd.sock:/var/run/tappd.sock
    restart: always
    command: >
      sh -c 'node dist/main-wallet-service.js'
