version: '3.8'

services:
  phala:
    image: phalanetwork/tappd-simulator:latest
    container_name: phala-tee-simulator
    ports:
      - "8090:8090"
    restart: always
    networks: 
    - core_local
  mongodb:
    image: mongo:4.4
    container_name: mongodb
    ports:
      - "27017:27017"
    restart: always
    environment:
      - MONGO_REPL_SET_NAME=rs0
    command: >
      bash -c "
        mongod --replSet rs0 --bind_ip 0.0.0.0 --bind_ip_all &
        sleep 5 &&
        mongo mongodb:27017 --eval 'rs.initiate()' &&
        wait"
    volumes:
      - ./.db_data/mongo:/data/db
    healthcheck:
      test: ["CMD", "mongo", "--eval", "rs.status()"]
      start_period: 5s
      interval: 5s
      retries: 10
      timeout: 30s
  core:
    image: xnomadai/core:0.1.2
    container_name: core
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - ./.db_data/agent:/app/db_data/agent
      - .env:/app/.env
      - .env.agent-eliza:/app/.env.agent-eliza
    #      - /var/run/tappd.sock:/var/run/tappd.sock
    restart: always
    env_file:
      - .env
      - .env.agent-eliza
    depends_on:
      - mongodb
    command: >
      sh -c '
        node dist/main.js'
networks:
  core_local:
    driver: bridge
